services:
  db:
    image: postgres:17-alpine
    container_name: db_ecommerce
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_ecommerce:/var/lib/postgresql/data

  backend:
    build: .
    container_name: backend_ecommerce
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DATABASE: ecommerce_db
      DB_SSL: "false" # Added this to control SSL
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  postgres_ecommerce:
    driver: local
